version: "3"
services:
  jenkins-master:
    build:
      context: ./docker/images/jenkins-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/volumes/jenkins-home:/var/jenkins_home:cached
    ports:
      - 8080:8080   # Jenkins UI
      - 8000:8000   # Jenkins Master Debugging Port
      - 50000:50000 # Jenkins JNLP port
    environment:
      - TRY_UPGRADE_IF_NO_MARKER=true
      - JAVA_OPTS= -Dstapler.jelly.noCache=true  -Dhudson.remoting.ClassFilter=com.google.common.collect.ImmutableListMultimap -DexecutableWar.jetty.disableCustomSessionIdCookieName=true -DexecutableWar.jetty.sessionIdCookieName=warnings-ng-devenv -agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    user: ${CURRENT_UID}
    restart: always
  java-agent:
    build: ./docker/images/java-agent
    ports:
      - 8001:8001   # Jenkins Agent Debugging Port
    depends_on:
      - jenkins-master
    restart: always
